<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>InvoiceFlow.BuildingBlocks.Domain</PackageId>
    <Description>
        Shared domain building blocks for InvoiceFlow microservices.
    </Description>
  </PropertyGroup>

</Project>
