<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\InvoiceFlow.Common.Application\InvoiceFlow.Common.Application.csproj" />
    <ProjectReference Include="..\InvoiceFlow.Customers.Domain\InvoiceFlow.Customers.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Customers\Commands\" />
  </ItemGroup>

</Project>
