<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="InvoiceFlow.BuildingBlocks.Application" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InvoiceFlow.Identity.Domain\InvoiceFlow.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Commands\" />
    <Folder Include="Features\PlatformUsers\Commands\" />
    <Folder Include="Features\Tenants\Commands\" />
  </ItemGroup>

</Project>
