<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\InvoiceFlow.BuildingBlocks.Application\InvoiceFlow.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\InvoiceFlow.Identity.Domain\InvoiceFlow.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\PlatformUsers\Commands\" />
    <Folder Include="Features\Roles\Commands\" />
    <Folder Include="Features\Tenants\Commands\" />
  </ItemGroup>

</Project>
