name: Identity CI

on:
  workflow_call:

jobs:
  placeholder:
    name: Identity Placeholder
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: echo "Identity CI not implemented yet."
